import React from 'react'
import DynamicTable from './DynamicTable'
const data=[
    {   id:1,
        name:'KLCC Charger',
        status:'available',
        number:1,
        type:'CCS2'
    },
    {   id:2,
        name:'KLCC Charger',
        status:'available',
        number:2,
        type:'CCS2'
    },
    {   id:3,
        name:'KLCC Charger',
        status:'available',
        number:3,
        type:'CCS2'
    },
    {   id:4,
        name:'KLCC Charger',
        status:'available',
        number:4,
        type:'CCS2'
    },
    {   id:5,
        name:'Xpark Charger',
        status:'available',
        number:1,
        type:'CCS2'
    },
    {   id:6,
        name:'Xpark Charger',
        status:'available',
        number:2,
        type:'CCS2'
    },
    {   id:7,
        name:'Xpark Charger',
        status:'available',
        number:3,
        type:'CCS2',
    },
    {   id:8,
        name:'Xpark Charger',
        status:'occupied',
        number:4,
        type:'CCS2',
    },
    {   id:9,
        name:'One Utama Charger',
        status:'occupied',
        number:1,
        type:'CCS2',
    },
    {   id:10,
        name:'One Utama Charger',
        status:'occupied',
        number:2,
        type:'CCS2',
    },
    {   id:11,
        name:'One Utama Charger',
        status:'occupied',
        number:3,
        type:'CCS2',
    },
    {   id:12,
        name:'One Utama Charger',
        status:'available',
        number:4,
        type:'CCS2',
    },
    {   id:13,
        name:'EVC Charger',
        status:'available',
        number:1,
        type:'CCS2',
    },
    {   id:14,
        name:'EVC Charger',
        status:'available',
        number:2,
        type:'CCS2',
    },
    {   id:15,
        name:'EVC Charger',
        status:'occupied',
        number:3,
        type:'CCS2',
    },
    {   id:16,
        name:'EVC Charger',
        status:'occupied',
        number:4,
        type:'CCS2',
    },
    {   id:17,
        name:'EVC x Gentary Charger',
        status:'occupied',
        number:1,
        type:'CCS2',
    },
    {   id:18,
        name:'EVC x Gentary Charger',
        status:'occupied',
        number:2,
        type:'CCS2',
    },
    {   id:19,
        name:'EVC x Gentary Charger',
        status:'occupied',
        number:3,
        type:'CCS2',
    },
    {   id:20,
        name:'EVC x Gentary Charger',
        status:'occupied',
        number:4,
        type:'CCS2',
    },
    
    
    
]
const ConnectorTable = () => {
  return (
    <div>
        <DynamicTable data={data} itemsPerPage={10} rename='Charge Station' title='Connectors'/>
    </div>
  )
}

export default ConnectorTable
